### ISSUE TITLE
StartTLS error in node 0.4.8

### ISSUE THREAD

**Issue by jhurliman** [weaver/node-mail#14]
```
var error = pair._ssl.verifyError();

TypeError: Cannot call method 'verifyError' of undefined
    at SecurePair.<anonymous> (/Users/johnhurliman/Code/cull/CullService/node_modules/mail/lib/starttls.js:18:27)
    at SecurePair.emit (events.js:61:17)
    at SecurePair.maybeInitFinished (tls.js:598:10)
    at CleartextStream._push (tls.js:269:17)
    at SecurePair.cycle (tls.js:574:20)
    at EncryptedStream.write (tls.js:96:13)
    at Socket.ondata (stream.js:36:26)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

According to an issue file at https://github.com/astro/node-xmpp/issues/21 and a comment at https://gist.github.com/848444 it appears that the undocumented tls.js had a breaking API change and `pair._ssl` is now `pair.ssl`. I propose changing the line to `var error = (pair.ssl) ? pair.ssl.verifyError() : pair._ssl.verifyError();`

**Comment by weaver** [comment]
Fixed, thanks for the patch!
